Repository grubflow/backend, pull requests merged in 2025-04, with the labels that each got.

#17 group capacity field
  conftest.py
  groups/migrations/0002_group_capacity.py
  groups/models.py
  groups/serializers.py
  groups/tests/group_invite_tests.py
  groups/views.py
  users/tests/user_tests.py
Labels: chore

#18 recipe endpoints
  common/permissions.py
  config/settings.py
  config/urls.py
  conftest.py
  groups/views.py
  recipes/__init__.py
  recipes/admin.py
  recipes/apps.py
  recipes/migrations/0001_initial.py
  recipes/migrations/__init__.py
  recipes/models.py
  recipes/serializers.py
  recipes/tests/ingredient_tests.py
  recipes/tests/recipe_tests.py
  recipes/tests/step_tests.py
  recipes/urls.py
  recipes/views.py
Labels: feature

#19 fix: 500 when updating recipe with put request
  recipes/serializers.py
Labels: bug

#20 simplify step_number input for step
  recipes/models.py
  recipes/serializers.py
  recipes/tests/recipe_tests.py
  recipes/tests/step_tests.py
Labels: chore

#21 Restaurants Endpoints
  config/settings.py
  config/urls.py
  conftest.py
  restaurants/__init__.py
  restaurants/admin.py
  restaurants/apps.py
  restaurants/migrations/0001_initial.py
  restaurants/migrations/__init__.py
  restaurants/models.py
  restaurants/serializers.py
  restaurants/tests/restaurant_tests.py
  restaurants/urls.py
  restaurants/views.py
Labels: feature

#22 hash image names
  recipes/migrations/0002_alter_recipe_options_alter_step_options_and_more.py
  recipes/serializers.py
  restaurants/serializers.py
  users/migrations/0003_alter_user_image.py
  users/models.py
Labels: chore
